Resources:
  DynamoDBIndexesClassroomEvents:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "organizerId"
          AttributeType: "S"
        - AttributeName: "time"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "DynamoDBIndexes-Test"
      GlobalSecondaryIndexes:
        - IndexName: "OrganizerIdTimeIndex"
          KeySchema:
            - AttributeName: "organizerId"
              KeyType: "HASH"
            - AttributeName: "time"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
